### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by jspark311** [LaboratoryB/stegosaurus#6]
I've already implemented lots of your TODO's, but it's in PHP. Your program and mine use the same modulation strategy.
https://github.com/jspark311/BuriedUnderTheNoiseFloor

I've been meaning to re-tool mine as a node library. Will you take PRs?

**Comment by dougbtv** [comment]
@jspark311 -- that would be.... much appreciated! Let me know if you run into any snags or want to brainstorm.

**Comment by dougbtv** [comment]
For now, just fork the code and submit PR's -- if it becomes a pain later, I'll add you a collaborator directly on the project.

**Comment by jspark311** [comment]
Thx  :-)
Forked.
I realized my project's license was GPL2, so I just made it more permissive. Feel free to gank ideas out of it.

Thinking of using this for the compression:
https://github.com/cscott/compressjs

I'll reply back once I've improved things.

**Comment by dougbtv** [comment]
Sounds great / great idea. I like that package too, I've used it for gzip /
bzip2 before. How data is packed in efficiently needs a desperate overhaul,
appreciate you digging in.
